name:                jot
version:             0.1.0.0
github:              "jakewilson/jot"
license:             BSD3
author:              "Jake Wilson"
maintainer:          "jakewilsonfl@protonmail.com"
copyright:           "Jake Wilson"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/jot#readme>

dependencies:
- base >= 4.7 && < 5
- text
- aeson
- directory
- bytestring
- utf8-string
- time
- containers

library:
  source-dirs: src

executables:
  jot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jot

tests:
  jot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jot
